controllers:
    resource: ../src/Controller/
    type: attribute

app_api:
    ressource: ''../src/Controller/Api'
    type: annotation
    prefix: '/api'

avis: 
    ressource: App\Controller\AvisController
    type: annotation